"""add_catalog_fields

Revision ID: 44b4df8a1650
Revises: 
Create Date: 2026-09-05 10:51:50.973324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44b4df8a1650'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment="Type of event (e.g. 'quote.proposed', 'order.payment_captured')"),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False, comment='Type of aggregate that triggered the event'),
    sa.Column('aggregate_id', sa.String(length=36), nullable=False, comment='ID of the aggregate object (quote_id, order_id, etc.)'),
    sa.Column('actor_id', sa.String(length=255), nullable=True, comment='ID of the actor (buyer_session, merchant_agent, etc.)'),
    sa.Column('actor_type', sa.String(length=20), nullable=True, comment="Type of actor ('buyer', 'merchant', 'system', 'policy', 'agent')"),
    sa.Column('payload', sa.JSON(), nullable=False, comment='Structured data specific to the event type'),
    sa.Column('explanation', sa.String(), nullable=True, comment='Human-readable explanation of why this event occurred'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_table('merchants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True, comment='BCrypt/Argon2 hash of merchant API key'),
    sa.Column('config', sa.JSON(), nullable=False, comment='Merchant-specific configuration (discount caps, etc.)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("name != ''", name=op.f('ck_merchants_ck_merchant_name_not_empty')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('negotiation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("role IN ('buyer', 'merchant', 'system')", name=op.f('ck_messages_ck_message_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_table('negotiations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=255), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'quote_proposed', 'accepted', 'rejected', 'expired', 'cancelled')", name=op.f('ck_negotiations_ck_negotiation_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_negotiations'))
    )
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price_cents', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_ck_orderitem_quantity_positive')),
    sa.CheckConstraint('unit_price_cents > 0', name=op.f('ck_order_items_ck_orderitem_price_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('buyer_id', sa.String(length=255), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_cents', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=64), nullable=True),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.CheckConstraint("idempotency_key != ''", name=op.f('ck_orders_ck_order_idempotency_key_not_empty')),
    sa.CheckConstraint("status IN ('created', 'pending_payment', 'payment_initiated', 'payment_captured', 'payment_failed', 'refunded', 'cancelled', 'completed')", name=op.f('ck_orders_ck_order_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_orders_idempotency_key'))
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ai_schema', sa.JSON(), nullable=False, comment='Structured data for LLM consumption (category, tags, specs, etc.)'),
    sa.Column('price_cents', sa.Integer(), nullable=False, comment='Price in paise (1 INR = 100 paise). Integer to avoid float issues.'),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=False, comment='Inventory stock quantity. Check: >= 0.'),
    sa.Column('compatible_product_ids', sa.JSON(), nullable=False, comment='List of product IDs compatible with this product'),
    sa.Column('use_cases', sa.JSON(), nullable=False, comment="List of use case strings (e.g. 'gym', 'commute', 'work')"),
    sa.Column('categories', sa.JSON(), nullable=False, comment='List of category strings this product belongs to'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag - inactive products are hidden from catalog'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint('price_cents > 0', name=op.f('ck_products_ck_product_price_positive')),
    sa.CheckConstraint('stock_qty >= 0', name=op.f('ck_products_ck_product_stock_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('quote_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price_cents', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_quote_items_ck_quoteitem_quantity_positive')),
    sa.CheckConstraint('unit_price_cents > 0', name=op.f('ck_quote_items_ck_quoteitem_price_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_items'))
    )
    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('negotiation_id', sa.String(length=36), nullable=True),
    sa.Column('proposed_by', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal_cents', sa.INTEGER(), nullable=False),
    sa.Column('discount_cents', sa.INTEGER(), nullable=False),
    sa.Column('tax_cents', sa.INTEGER(), nullable=False),
    sa.Column('total_cents', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('policy_decision', sa.String(length=20), nullable=True),
    sa.Column('policy_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("proposed_by IN ('buyer', 'merchant', 'system')", name=op.f('ck_quotes_ck_quote_proposed_by')),
    sa.CheckConstraint("status IN ('draft', 'pending_review', 'approved', 'rejected', 'expired', 'accepted')", name=op.f('ck_quotes_ck_quote_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quotes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    op.drop_table('quote_items')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('order_items')
    op.drop_table('negotiations')
    op.drop_table('messages')
    op.drop_table('merchants')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
