"""Pydantic request/response schemas for the AI Merchant Platform."""

from .growth import (
    BuyerIntent,
    ProductScore,
    UpsellOpportunity,
    BundleRecommendation,
    GrowthBrainOutput,
)
from .negotiation import (
    NegotiationStatus,
    MessageRole,
    QuoteStatus,
    PolicyVerdict,
    ProposedBy,
    QuoteItemInput,
    QuoteProposal,
    NegotiationStart,
    QuoteItemOutput,
    QuoteOutput,
    MessageOutput,
    NegotiationState,
    PolicyCheckResult,
    PolicyEvaluationOutput,
    NegotiationActionResult,
    MAX_ROUNDS,
    MAX_TURNS,
    QUOTE_VALIDITY_MINUTES,
    DEFAULT_DISCOUNT_CAP_PCT,
    MIN_ORDER_VALUE_CENTS,
    MAX_AUTO_APPROVE_CENTS,
)

__all__ = [
    "BuyerIntent",
    "ProductScore",
    "UpsellOpportunity",
    "BundleRecommendation",
    "GrowthBrainOutput",
    "NegotiationStatus",
    "MessageRole",
    "QuoteStatus",
    "PolicyVerdict",
    "ProposedBy",
    "QuoteItemInput",
    "QuoteProposal",
    "NegotiationStart",
    "QuoteItemOutput",
    "QuoteOutput",
    "MessageOutput",
    "NegotiationState",
    "PolicyCheckResult",
    "PolicyEvaluationOutput",
    "NegotiationActionResult",
    "MAX_ROUNDS",
    "MAX_TURNS",
    "QUOTE_VALIDITY_MINUTES",
    "DEFAULT_DISCOUNT_CAP_PCT",
    "MIN_ORDER_VALUE_CENTS",
    "MAX_AUTO_APPROVE_CENTS",
]